import Link from 'next/link'
import '../styles/global.css'
import Header from './components/nav'

export const metadata = {
  title: 'Next-Blog',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
